### ISSUE TITLE
Not working in mobile.

### ISSUE THREAD

**Issue by developeronboard** [martyf/tinymce-5-plugin-with-dialog#4]
Dropdown was not triggering and not displaying in mobile. How to make this to work in a mobile browsers, any suggestions please?

**Comment by martyf** [comment]
Can you provide more information please.

I am not experiencing issues on mobile devices.

**Comment by developeronboard** [comment]
![tinymce martyfield com](https://user-images.githubusercontent.com/61226091/80338232-6aa77080-8879-11ea-9af5-9ffcf474ca98.jpg)
![martyfieldblog](https://user-images.githubusercontent.com/61226091/80338249-772bc900-8879-11ea-9143-49ed3aeaf391.jpg)
Yes sure, these are two links you had provided demo for autocomplete plugin.When I open thess links in my mobile the dropdown was not rendering. Whether any changes should be made my side ?Please advice regarding this.
Thank you

**Comment by martyf** [comment]
I'd suggest looking at your developer logs for your mobile browser to see what output is provided. 

I'm on iOS and don't have access to an Android device at the moment sorry, and have no issues with the Autocompleter on iOS.

If there's an issue on a specific device/browser version, it could either be a quirk with your browser, or an issue that needs to be addressed higher up with Tiny itself. If you can provide further information (such as errors that may be generated) that is useful.

**Comment by developeronboard** [comment]
Ok thanks @martyf

**Comment by developeronboard** [comment]
@martyf It was a tinymce known issue they were not capturing '@' in android devices. But autocomplete was trigeering with all other special characters like `!,#,$,&,*`

**Comment by martyf** [comment]
Ah cool bananas - thank you for the update @developeronboard, that's handy to know. I guess it is showing my users who are using an autocomplete plugin must be on iOS (or non-mobile) as I'd not heard of that. Thanks for coming back to me with that, I appreciate it.
